# Generated by Django 3.2.7 on 2021-09-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField()),
                ('level', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=512)),
                ('guid', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('surname', models.CharField(max_length=512)),
                ('mail', models.CharField(max_length=512)),
                ('affiliation', models.CharField(max_length=512)),
            ],
        ),
    ]
