# Generated by Django 3.2.7 on 2021-09-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='affiliation',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('maker', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('date_added', models.DateTimeField()),
                ('state', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.location')),
            ],
        ),
        migrations.CreateModel(
            name='CameraConfigurationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=65536, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=512)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.sensor')),
            ],
        ),
    ]
