# Generated by Django 3.2.7 on 2021-09-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0002_auto_20210907_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=512)),
                ('species', models.CharField(max_length=30)),
                ('interaction', models.CharField(max_length=30)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('guid', models.UUIDField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbms.location')),
                ('referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referent', to='dbms.person')),
                ('researcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher', to='dbms.person')),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbms.location'),
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('species', models.CharField(max_length=30)),
                ('treatment', models.CharField(max_length=30)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('filename', models.CharField(max_length=65536)),
                ('angle', models.FloatField()),
                ('wavelength', models.IntegerField()),
                ('guid', models.UUIDField()),
                ('cam_settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbms.cameraconfigurationfile')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_camera', to='dbms.plant')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.experiment')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_plant', to='dbms.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('guid', models.UUIDField()),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbms.plant')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbms.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='DataIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=65536, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=512)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=65536, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=512)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.experiment')),
            ],
        ),
    ]
