# Generated by Django 3.2.7 on 2021-09-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0004_auto_20210907_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_camera', to='dbms.sensor'),
        ),
    ]
