# Generated by Django 3.2.7 on 2021-09-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0005_alter_photo_camera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='target_id',
        ),
        migrations.AddField(
            model_name='annotation',
            name='analysis_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.analysisresult'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='camera_conf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.cameraconfigurationfile'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='data_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.datain'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.experiment'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.location'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.measure'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.person'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.photo'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.sensor'),
        ),
    ]
