# Generated by Django 3.2.7 on 2021-09-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0006_auto_20210907_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='analysis_result',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='camera_conf',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='data_in',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='person',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='sensor',
        ),
        migrations.AddField(
            model_name='annotation',
            name='target_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='annotation',
            name='target_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
