# Generated by Django 3.2.7 on 2021-09-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0007_auto_20210907_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='filename',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='guid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='level',
            field=models.CharField(choices=[('d', 'DEBUG'), ('i', 'INFO'), ('w', 'WARNING'), ('e', 'ERROR'), ('c', 'CRITICAL')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cameraconfigurationfile',
            name='filename',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='datain',
            name='filename',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
