# Generated by Django 3.2.7 on 2021-09-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0011_auto_20210909_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='guid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='guid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='guid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='guid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
