# Generated by Django 3.2.7 on 2021-09-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0012_auto_20210909_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='guid',
        ),
        migrations.AddField(
            model_name='photo',
            name='job_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='photo',
            name='angle',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='wavelength',
            field=models.CharField(max_length=30),
        ),
    ]
