# Generated by Django 3.2.7 on 2021-09-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0014_experiment_allowed_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='guid',
        ),
        migrations.AddField(
            model_name='measure',
            name='job_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='state',
            field=models.CharField(choices=[('d', 'DEBUG'), ('i', 'INFO'), ('w', 'WARNING'), ('e', 'ERROR'), ('c', 'CRITICAL')], max_length=30),
        ),
    ]
