# Generated by Django 3.2.7 on 2021-09-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0016_auto_20210913_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='level',
            field=models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=30),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DISCARDED', 'DISCARDED'), ('REPAIRING', 'REPAIRING'), ('STORED', 'STORED')], default='ACTIVE', max_length=30),
        ),
    ]
