# Generated by Django 3.2.7 on 2021-09-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0017_auto_20210913_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='plant',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='state',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('ACTIVE', 'ACTIVE'), ('DISCARDED', 'DISCARDED'), ('REPAIRING', 'REPAIRING'), ('STORED', 'STORED')], default='ACTIVE', max_length=30),
        ),
        migrations.CreateModel(
            name='Weighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('job_id', models.IntegerField(default=-1)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbms.plant')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbms.sensor')),
            ],
        ),
    ]
