# Generated by Django 3.2.7 on 2021-09-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0018_auto_20210913_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
