# Generated by Django 3.2.7 on 2021-09-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0019_alter_annotation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraconfigurationfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
