# Generated by Django 3.2.7 on 2021-09-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0020_auto_20210914_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
