# Generated by Django 3.2.7 on 2021-09-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0021_location_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='cam_settings',
        ),
        migrations.AddField(
            model_name='datain',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='cam_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbms.cameraconfigurationfile'),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
