# Generated by Django 3.2.7 on 2021-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0022_auto_20210916_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='target_class_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
