# Generated by Django 3.2.7 on 2021-09-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0024_auto_20210920_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(unique=True, upload_to='')),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.experiment')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
    ]
