# Generated by Django 3.2.7 on 2021-09-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0025_analysisprotocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbms.person'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbms.sensor'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbms.plant'),
        ),
    ]
